export const tickets = [
    {
        id:1,
        title:'مشکل در سرعت سایت',
        priority:'HIGH',
        costumer:1,
        description:'توضیحات سرعت سایت',
        product:2,
        department:1,
        answerStatus:false,
        rate:undefined,
        submissionDateTime:'not-set',
    },
    {
        id:2,
        title:'تغییر ip سرور',
        priority:'LOW',
        costumer:4,
        description:'توضیحات ip',
        product:6,
        department:3,
        answerStatus:false,
        rate:undefined,
        submissionDateTime:'not-set',
    },
    {
        id:3,
        title:'کرش کردن اپلیکیشن',
        priority:'MEDIUM',
        costumer:3,
        description:'توضیحات برای اپلیکیشن',
        product:3,
        department:2,
        answerStatus:false,
        rate:undefined,
        submissionDateTime:'not-set',
    },
    {
        id:4,
        title:'باز نشدن پنل مدیریت',
        priority:'HIGH',
        costumer:5,
        description:'توضیحات برای پنل مدیریت ',
        product:1,
        department:1,
        answerStatus:false,
        rate:undefined,
        submissionDateTime:'not-set',
    },
];