export const tickets = [
    {
        id:1,
        title:'مشکل در سرعت سایت',
        priority:'HIGH',
        costumer:1,
        product:2,
        department:1,
        answerStatus:false,
        submissionDateTime:'not-set',
    },
    {
        id:2,
        title:'تغییر ip سرور',
        priority:'LOW',
        costumer:4,
        product:6,
        department:3,
        answerStatus:false,
        submissionDateTime:'not-set',
    },
    {
        id:3,
        title:'کرش کردن اپلیکیشن',
        priority:'MEDIUM',
        costumer:3,
        product:3,
        department:2,
        answerStatus:false,
        submissionDateTime:'not-set',
    },
    {
        id:4,
        title:'باز نشدن پنل مدیریت',
        priority:'HIGH',
        costumer:5,
        product:1,
        department:1,
        answerStatus:false,
        submissionDateTime:'not-set',
    },
];