import moment from 'moment-jalaali';

export const tickets = [
    {
        id: 1,
        title: 'مشکل در سرعت سایت',
        priority: 'HIGH',
        costumer: 1,
        comment: undefined,
        description: 'توضیحات سرعت سایت',
        product: 2,
        department: 1,
        answerStatus: false,
        rate: undefined,
        submissionDateTime: moment().format('jYYYY/jMM/jDD'),
    },
    {
        id: 2,
        title: 'تغییر ip سرور',
        priority: 'LOW',
        costumer: 4,
        comment: undefined,
        description: 'توضیحات ip',
        product: 6,
        department: 3,
        answerStatus: false,
        rate: undefined,
        submissionDateTime: moment().subtract(3, 'days').format('jYYYY/jMM/jDD'),
    },
    {
        id: 3,
        title: 'کرش کردن اپلیکیشن',
        priority: 'MEDIUM',
        costumer: 3,
        comment: undefined,
        description: 'توضیحات برای اپلیکیشن',
        product: 3,
        department: 2,
        answerStatus: true,
        rate: undefined,
        submissionDateTime: moment().subtract(1, 'months').format('jYYYY/jMM/jDD'),
    },
    {
        id: 4,
        title: 'باز نشدن پنل مدیریت',
        priority: 'HIGH',
        costumer: 5,
        comment: undefined,
        description: 'توضیحات برای پنل مدیریت ',
        product: 1,
        department: 1,
        answerStatus: false,
        rate: undefined,
        submissionDateTime: moment().subtract(3, 'days').format('jYYYY/jMM/jDD'),
    },
];