import moment from 'moment-jalaali';

export const transactions = [
    {
        id:1,
        costumer:1,
        product:2,
        expireDate:moment().add(5,'months')
    },
    {
        id:2,
        costumer:1,
        product:5,
        expireDate:moment().add(1,'months')
    },
    {
        id:3,
        costumer:1,
        product:1,
        expireDate:moment().add(1,'years')
    },
    {
        id:4,
        costumer:2,
        product:6,
        expireDate:moment().add(5,'months')
    },
    {
        id:5,
        costumer:2,
        product:2,
        expireDate:moment().add(8,'months')
    },
    {
        id:6,
        costumer:4,
        product:1,
        expireDate:moment().add(5,'days')
    },
    {
        id:7,
        costumer:4,
        product:3,
        expireDate:moment().add(3,'months')
    },
    {
        id:8,
        costumer:5,
        product:6,
        expireDate:moment().add(5,'months')
    },
    {
        id:9,
        costumer:5,
        product:1,
        expireDate:moment().add(5,'months')
    }
];